# @package dataset
name: nadig25hepg2
data_path: data/nadig25hepg2/nadig25hepg2_processed_complete.h5ad
description: "Nadig25 HepG2 dataset"
covariate_key: donor_id

# Universal baselines (same across all folds)
ground_truth_baseline_key: technical_duplicate_first_half_baseline
technical_duplicate_baseline_key: technical_duplicate_second_half_baseline
additive_baseline_key: null 
sparse_mean_baseline_key: sparse_mean_baseline_seed_0  # Additional baseline to report
interpolated_duplicate_baseline_key: interpolated_duplicate_baseline
control_baseline_key: ctrl_baseline

# Define all folds
folds:
  - split: split_fold_0
    dataset_mean_baseline_key: split_fold_0_mean_baseline
    linear_baseline_key: split_fold_0_linear_baseline
  
  - split: split_fold_1
    dataset_mean_baseline_key: split_fold_1_mean_baseline
    linear_baseline_key: split_fold_1_linear_baseline
  
  - split: split_fold_2
    dataset_mean_baseline_key: split_fold_2_mean_baseline
    linear_baseline_key: split_fold_2_linear_baseline
  
  - split: split_fold_3
    dataset_mean_baseline_key: split_fold_3_mean_baseline
    linear_baseline_key: split_fold_3_linear_baseline
  
  - split: split_fold_4
    dataset_mean_baseline_key: split_fold_4_mean_baseline
    linear_baseline_key: split_fold_4_linear_baseline

# Default fold to use when not doing k-fold
default_fold: 0

